pythonProject/taskmanager/main/urls.py
#from django.contrib import admin
from django.urls import path, include
from . import views


app_name = 'main'
urlpatterns = [
    #path('admin/', admin.site.urls),
    #path('', include('main.urls'))
    path('', views.index, name='home'),
    path('about-us', views.about, name='about'),
    path('register', views.register, name='register'),
    path('login', views.login, name='login'),
    path('profile/', views.profile, name='profile'),
    path('logout', views.logout, name='logout'),

]

pythonProject/taskmanager/taskmanager/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls'))

]

pythonProject/taskmanager/main/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
# Create your models here.


class Task(models.Model):
    title = models.TextField('Название')
    task = models.TextField('Описание')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Задача'
        verbose_name_plural = 'Задачи'

pythonProject/taskmanager/main/forms.py
from .models import Task
from django.forms import ModelForm, TextInput, DateInput, Textarea, FileInput
from django.contrib.auth.models import User
from django.contrib import auth
from django.contrib.auth.forms import UserCreationForm
from django import forms


class Works(forms.Form):
    AVTOR = (
        ("Leskov", "Лесков"),
        ("Tolstoy", "Толстой"),
        ("Sber", "Сбер"))
    input1 = forms.CharField(label="Ваш текст",widget=forms.Textarea(attrs={'cols':60, 'rows': 10}))
    input2 = forms.ChoiceField(label="Автор", choices=AVTOR)

pythonProject/taskmanager/main/views.py
from django.shortcuts import render

import numpy as np
import torch
# Create your views here.

from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from transformers import GPT2LMHeadModel, GPT2Tokenizer
from .forms import *
from .models import Task
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from django.contrib import auth
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.views.decorators.csrf import csrf_protect


def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Регистрация прошла успешно')
            return redirect('main:login')
        else:
            messages.error(request, 'Ошибка регистрации')
    else:
        form = UserCreationForm()
    return render(request, 'main/registr.html', {"form": form})


def login(request):
    return render(request, 'main/login.html')


def index(request):

    return render(request, 'main/index.html', {'title': 'Главная страница сайта'})


def about(request):
    return render(request, 'main/about.html')





@csrf_protect
def login(request):
    data = {}

    if request.POST:
        username = request.POST.get('username', '')
        password = request.POST.get('password', '')
        user = auth.authenticate(username=username, password=password)
        if user is not None:
            auth.login(request, user)
            return render(request, 'main/index.html')
        else:
            data['login_error'] = "Проверьте правилность данных"
            return render(request, 'main/login.html', data)
    else:
        return render(request, 'main/login.html', data)

@csrf_protect
@login_required(login_url='/')
def profile(request):
    username = auth.get_user(request).username
    user = User.objects.get(username=username)
    if request.method == 'POST':

        form = Works(request.POST)
        Text = request.POST.get('input1', '')
        Choise = request.POST.get('input2', '')
        np.random.seed(42)
        torch.manual_seed(42)
        if Choise == "Leskov":
            model_name_or_path = "C:\\Pycharm\\pythonProject\\taskmanager\\main\\models\\L"
            tokenizer = GPT2Tokenizer.from_pretrained(model_name_or_path)
            model = GPT2LMHeadModel.from_pretrained(model_name_or_path).cpu()
            text = Text
            input_ids = tokenizer.encode(text, return_tensors="pt").cpu()
            out = model.generate(input_ids.cpu())
            generated_text = list(map(tokenizer.decode, out))[0]
            Text = generated_text
            return render(request, 'main/profile.html', {'user': user, 'form': form, 'Text': Text})
        if Choise == "Tolstoy":
            model_name_or_path = "C:\\Pycharm\\pythonProject\\taskmanager\\main\\models\\T"
            tokenizer = GPT2Tokenizer.from_pretrained(model_name_or_path)
            model = GPT2LMHeadModel.from_pretrained(model_name_or_path).cpu()
            text = Text
            input_ids = tokenizer.encode(text, return_tensors="pt").cpu()
            out = model.generate(input_ids.cpu())
            generated_text = list(map(tokenizer.decode, out))[0]
            Text = generated_text
            return render(request, 'main/profile.html', {'user': user, 'form': form, 'Text': Text})
        if Choise == "Sber":
            model_name_or_path = "sberbank-ai/rugpt3large_based_on_gpt2"
            tokenizer = GPT2Tokenizer.from_pretrained(model_name_or_path)
            model = GPT2LMHeadModel.from_pretrained(model_name_or_path).cpu()
            text = Text
            input_ids = tokenizer.encode(text, return_tensors="pt").cpu()
            out = model.generate(input_ids.cpu())
            generated_text = list(map(tokenizer.decode, out))[0]
            Text = generated_text
            return render(request, 'main/profile.html', {'user': user, 'form': form, 'Text': Text})

    else:
        Text = ""
        form = Works()
    return render(request, 'main/profile.html', {'user': user, 'form': form, 'Text': Text})


def logout(request):
    auth.logout(request)
    return render(request, 'main/login.html')

pythonProject/taskmanager/main/templates/main/about.html
{% extends 'main/base.html' %}

{% block title%}
О программе
{% endblock %}

{% block content%}
    <h1>О программе</h1>
    <p>Программа позволяет пользователю регистрироваться для составления его учётной записи.</p>
    <p>Программа позволяет пользователю авторизироваться для того, что-бы получать расшириный функционал сайта.</p>
    <p>Программа позволяет пользователю выполнять генерацию текста с учётом индивидуальных особенностей авторского стиля.</p>
    <p>Программа позволяет пользователю выходить из своей учётной записи.</p>
{% endblock %}

pythonProject/taskmanager/main/templates/main/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title%}{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css">
</head>
<body>
    <div class="d-flex flex-column flex-md-row align-items-center pb-3 mb-4 border-bottom">
        <h5 class="my-0 mr-md-auto font-weight-normal">Генератор текста</h5>
      <nav class="d-inline-flex mt-2 mt-md-0 ms-md-auto">

          <a class="me-3 py-2 text-dark text-decoration-none" href="{% url 'main:home' %}">Главная</a>
          <a class="me-3 py-2 text-dark text-decoration-none" href="{% url 'main:about' %}">О программе</a>
          <a class="me-3 py-2 text-dark text-decoration-none" href="{% url 'main:register' %}">Регистрация</a>
          {% if request.user.is_authenticated %}
            <a class="me-3 py-2 text-dark text-decoration-none" href="{% url 'main:logout' %}">Выйти</a>
            <a class="me-3 py-2 text-dark text-decoration-none" href="{% url 'main:profile' %}">Рабочая зона</a>
            {% else %}
            <a class="me-3 py-2 text-dark text-decoration-none" href="{% url 'main:login' %}">Авторизация</a>
          {% endif %}
      </nav>
    </div>

    {% block content%}{% endblock %}

</body>
</html>

pythonProject/taskmanager/main/templates/main/index.html
{% extends 'main/base.html' %}

{% block title%}
{{ title }}
{% endblock %}

{% block content%}
    <h1>Главная страница.</h1>
    <p>Это главная начальная страница сайта.</p>
    <p>Рекомендуем прочитать информацию о программе перейдя по ссылке "О программе".</p>
    <p>Рекомендуем выполнить регистрацию и авторизацию перейдя по ссылкам "Регистрация" и "Авторизация".</p>


{% endblock %}

pythonProject/taskmanager/main/templates/main/login.html
{% extends 'main/base.html' %}

{% block title%}
Авторизация
{% endblock %}

{% block content%}
        <form action="{% url 'main:login' %}" method="post">
        <h1>Авторизация</h1>
        {% csrf_token %}<br>
        <label for="username">Имя пользователя</label>
        <input type="text" name="username" id="username"><br><br>
        <label for="password">Пароль</label>
        <input type="password" name="password" id="password"><br><br>
        {% if login_error %}
        <label class="error">{{ login_error }}</label><br><br>
        {% endif %}
        <button class="btn btn-success" type="submit">Войти</button>
        </form>
{% endblock %}

pythonProject/taskmanager/main/templates/main/profile.html
{% extends 'main/base.html' %}

{% block title%}
Рабочая зона
{% endblock %}
{% block content%}
  <h1>Рабочая зона</h1>
        <form action="{% url 'main:profile' %}" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button class="btn btn-success" type="submit">Начать генерацию</button>
                <h2>Вывод</h2>
                <div class ="alert alert-warning mt-2">
                    <h3>{{ Text }}</h3>
                </div>
        </form>
{% endblock %}

pythonProject/taskmanager/main/templates/main/registr.html
{% extends 'main/base.html' %}

{% block title%}
Регистрация
{% endblock %}
{% block content%}
    <h1>Регистрация</h1>
    <p>Введите:</p>


    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}

        <button type="submit" class="btn btn-primary btn-block">Отправить
        </button>

    </form>
{% endblock %}